
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.provider = 'virtualbox'

  config.vm.define "net1" do | p |
    p.vm.box = 'generic/debian10'
    p.vm.box_url = "https://vagrant.comcloud.xyz/generic/boxes/debian10/versions/4.1.10/providers/virtualbox.box"
    p.vm.host_name = "net1"
    p.vm.network  "public_network", bridge: "enp2s0"
    p.vm.network  "private_network", ip: "192.168.1.1"

    p.vm.provider :virtualbox do |res|
        res.customize ["modifyvm", :id, "--cpus", "1"]
        res.customize ["modifyvm", :id, "--memory", "1500"]
    end
  end

  # config.vm.define "net2" do | b |
  #   b.vm.box = 'generic/debian10'
  #   b.vm.box_url = "https://vagrant.comcloud.xyz/generic/boxes/debian10/versions/4.1.10/providers/virtualbox.box"
  #   b.vm.host_name = "net2"

  #   b.vm.network  "public_network", bridge: "enp2s0"
  #   b.vm.network  "private_network", ip: "192.168.1.2"

  #   b.vm.provider :virtualbox do |res|
  #       res.customize ["modifyvm", :id, "--cpus", "1"]
  #       res.customize ["modifyvm", :id, "--memory", "1500"]
  #   end
  # end

  # config.vm.define "net3" do | p |
  #   p.vm.box = 'generic/debian10'
  #   p.vm.box_url = "https://vagrant.comcloud.xyz/generic/boxes/debian10/versions/4.1.10/providers/virtualbox.box"
  #   p.vm.host_name = "net3"
  #   p.vm.network  "public_network", bridge: "enp2s0"
  #   p.vm.network  "private_network", ip: "192.168.1.3"

  #   p.vm.provider :virtualbox do |res|
  #       res.customize ["modifyvm", :id, "--cpus", "1"]
  #       res.customize ["modifyvm", :id, "--memory", "1500"]
  #   end
  # end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end